rules:
    indentation:
        - 2
        -
            size: 4
    no-empty-rulesets: 0
    no-css-comments: 0
    brace-style: 0
    leading-zero: 0
    force-pseudo-nesting: 0
    force-element-nesting: 0

